apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev

images:
- name: docker.io/tomasignacio/backend
  newName: tomasignacio/backend
  newTag: cb209c9bec4e8e89802524fee101fd42f3a140dd
- name: docker.io/tomasignacio/frontend
  newName: tomasignacio/frontend
  newTag: cb209c9bec4e8e89802524fee101fd42f3a140dd
