apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev

images:
- name: docker.io/tomasignacio/backend
  newName: tomasignacio/backend
  newTag: 0fb1f8fb33bccee95c9003b02c5b833ea057840c
- name: docker.io/tomasignacio/frontend
  newName: tomasignacio/frontend
  newTag: 0fb1f8fb33bccee95c9003b02c5b833ea057840c
