apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: dev
images:
  - name: docker.io/tomasignacio/backend
    newName: docker.io/tomasignacio/backend
    newTag: "latest"
  - name: docker.io/tomasignacio/frontend
    newName: docker.io/tomasignacio/frontend
    newTag: "latest"