apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - sealedsecret.yaml
  - sealedsecret.yaml
  - ingress.yaml
  - sealedsecret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
